# Generated by Django 4.2.5 on 2023-09-29 20:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import sepulka.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sepulka',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='name')),
                ('is_warm', models.BooleanField(default=False, verbose_name='is warm')),
                ('is_square', models.BooleanField(default=False, verbose_name='is square')),
                ('is_soft', models.BooleanField(default=False, verbose_name='is soft')),
                ('size', models.CharField(choices=[('XS', 'Xs'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl'), ('XXL', 'Xxl')], default='M', max_length=3, verbose_name='size')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'deleted'), (1, 'created'), (2, 'in process'), (3, 'processed'), (4, 'in delivery'), (5, 'completed')], default=1, verbose_name='state')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, validators=[sepulka.validators.validate_user_shmurdik], verbose_name='user creator')),
            ],
            options={
                'verbose_name': 'sepulka',
                'verbose_name_plural': 'sepulki',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vaccinated', models.BooleanField(default=False, verbose_name='is vaccinated')),
                ('is_processed', models.BooleanField(default=False, verbose_name='is processed')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('responsible', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, validators=[sepulka.validators.validate_user_grymzik], verbose_name='responsible user')),
                ('sepulka', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sepulka.sepulka', verbose_name='sepulka')),
            ],
            options={
                'verbose_name': 'sepulka process',
                'verbose_name_plural': 'sepulka processes',
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256, verbose_name='message')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('sepulka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sepulka.sepulka', verbose_name='sepulka')),
            ],
            options={
                'verbose_name': 'sepulka flow',
                'verbose_name_plural': 'sepulka flows',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('SDEL', 'self delivery'), ('ROLL', 'roll'), ('AIRB', 'air balloon')], default=None, max_length=4, null=True, verbose_name='type')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('responsible', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, validators=[sepulka.validators.validate_user_fufelnitsa], verbose_name='responsible user')),
                ('sepulka', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sepulka.sepulka', verbose_name='sepulka')),
            ],
            options={
                'verbose_name': 'sepulka delivery',
                'verbose_name_plural': 'sepulka deliveries',
            },
        ),
    ]
